# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: quay.io/prometheus/alertmanager
  pullPolicy: IfNotPresent
  tag: ""

service:
  annotations: {}
  type: ClusterIP
  port: 9093
  loadBalancerIP: ""  # Assign ext IP when Service type is LoadBalancer
  loadBalancerSourceRanges: []  # Only allow access to loadBalancerIP from these IPs

ingress:
  enabled: true
  className: "cilium"
  annotations:
    #kubernetes.io/ingress.class: cilium
    ingress.cilium.io/loadbalancer-mode: 'shared'
    ingress.cilium.io/service-type: 'LoadBalancer'
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: alertmanager.magedu.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - alertmanager.domain.com

persistence:
  enabled: true
  storageClass: "openebs-hostpath"
  accessModes:
    - ReadWriteOnce
  size: 2Gi

config:
  enabled: true
  global: {}
    # slack_api_url: ''

  templates:
    - '/etc/alertmanager/*.tmpl'

  receivers:
    - name: default-receiver
      # slack_configs:
      #  - channel: '@you'
      #    send_resolved: true

  route:
    group_wait: 10s
    group_interval: 5m
    receiver: default-receiver
    repeat_interval: 3h

configmapReload:
  enabled: true

  name: configmap-reload

  image:
    repository: quay.io/prometheus-operator/prometheus-config-reloader
    tag: v0.66.0
    pullPolicy: IfNotPresent

templates: {}
#   alertmanager.tmpl: |-

