# Maintainer: MageEdu <mage@magedu.com>
#
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    route:
      receiver: 'default-receiver'
      group_wait: 30s
      group_interval: 30m
      group_by: [ alertname ]
    
    receivers:
      - name: 'default-receiver'
