replicas: 1

deploymentStrategy:
  type: RollingUpdate

service:
  enabled: true
  type: ClusterIP
  loadBalancerIP: ""
  port: 80
  targetPort: 3000
  annotations: {}
  portName: service

serviceMonitor:
  enabled: false

ingress:
  enabled: true
  annotations:
    ingress.cilium.io/loadbalancer-mode: 'shared'
    ingress.cilium.io/service-type: 'LoadBalancer'
    kubernetes.io/ingress.class: cilium
    # kubernetes.io/tls-acme: "true"
  path: /
  pathType: Prefix
  hosts:
    - grafana.magedu.com

persistence:
  type: pvc
  enabled: true
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  finalizers:
    - kubernetes.io/pvc-protection

# Administrator credentials when not using an existing secret (see below)
adminUser: admin
adminPassword: magedu.com

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - access: proxy
      basicAuth: false
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
      secureJsonData:
        httpHeaderValue1: "tenant1"
      editable: true
      isDefault: true
      name: loki
      type: loki
      uid: loki
      url: http://loki-gateway
      version: 1
  
    - access: proxy
      basicAuth: false
      editable: true
      isDefault: false
      name: prometheus
      type: prometheus
      uid: prometheus
      url: http://prometheus:9090
      version: 1

dashboards: {}
  # default:
  #   some-dashboard:
  #     json: |
  #       $RAW_JSON
  #   custom-dashboard:
  #     file: dashboards/custom-dashboard.json
  #   prometheus-stats:
  #     gnetId: 2
  #     revision: 2
  #     datasource: Prometheus
  #   local-dashboard:
  #     url: https://example.com/repository/test.json
  #     token: ''
  #   local-dashboard-base64:
  #     url: https://example.com/repository/test-b64.json
  #     token: ''
  #     b64content: true
  #   local-dashboard-gitlab:
  #     url: https://example.com/repository/test-gitlab.json
  #     gitlabToken: ''
  #   local-dashboard-bitbucket:
  #     url: https://example.com/repository/test-bitbucket.json
  #     bearerToken: ''
  #   local-dashboard-azure:
  #     url: https://example.com/repository/test-azure.json
  #     basic: ''
  #     acceptHeader: '*/*'

dashboardsConfigMaps: {}
#  default: ""
