apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: minio
scheduler:
  name: ""
spec:
  configuration:
    name: minio-env-configuration
  credsSecret:
    name: minio-secret
  exposeServices:
    console: true
  features: {}
  image: minio/minio:RELEASE.2024-04-18T19-09-19Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - minio
            - key: v1.min.io/pool
              operator: In
              values:
              - pool-0
          topologyKey: kubernetes.io/hostname
    name: pool-0
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
    runtimeClassName: ""
    servers: 3
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "10737418240"
        storageClassName: openebs-hostpath
      status: {}
    volumesPerServer: 2
  requestAutoCert: false
  users:
  - name: minio-user-0
